### ISSUE TITLE
BA3MSAT crashes at > 100 loci

### ISSUE THREAD

**Issue by SamWittwer** [brannala/BA3#2]
Hello

I am having issues running BayesAss with my data (baitSTR data for 602 loci, 63 individuals, 5 populations). As the description in the release states BA3MSAT is compiled to run up to 500 loci I subsampled my data down to 500 loci randomly, however, it crashed repeatedly. Further subsampling lead to the program running fine with 100 loci and crashing with 101 (segmentation fault).

When inspecting the source I found MAXLOCI=100 in BA3.h and changed this to 500. Now it runs fine with 101 loci so I'm assuming it'll run fine with 500 too. Two questions:

- Do i need to change anything else in the source code to allow the program to run with 500 loci?
- Could I also increase this value further to allow analysis of my full 602 loci dataset?

Thank you!

Samuel Wittwer

**Comment by brannala** [comment]
Hi Samuel,
Yes, what you have done is correct. The program uses dynamic 
memory allocation so further increases should be fine if you have 
sufficient memory resources on your machine. You can use a program 
like htop to monitor the memory usage if you are working on a Unix 
machine. Memory usage  will scale non-linearly with numbers of 
loci. The reason the MSAT version has so few loci is that it 
allows hundreds of alleles at each locus and most MSAT datasets 
have fewer than 100 loci (at least that used to be true). You can 
also decrease the maximum number of alleles to something close to 
the maximum in your dataset to save memory. I have been meaning to 
modify the code to check available memory resources rather than 
having fixed limits on the number of loci but haven't had a chance 
yet. When I do that I will then add more error checking as well so 
that the program exits gracefully when an out of memory condition 
occurs or a defined limit is exceeded rather than crashing. Let me 
know if you have any further issues.
Best wishes,
Bruce




Samuel Wittwer writes:

> Hello
>
> I am having issues running BayesAss with my data (baitSTR data 
> for 602 loci, 63 individuals, 5 populations). As the description 
> in the release states BA3MSAT is compiled to run up to 500 loci 
> I subsampled my data down to 500 loci randomly, however, it 
> crashed repeatedly. Further subsampling lead to the program 
> running fine with 100 loci and crashing with 101 (segmentation 
> fault).
>
> When inspecting the source I found MAXLOCI=100 in BA3.h and 
> changed this to 500. Now it runs fine with 101 loci so I'm 
> assuming it'll run fine with 500 too. Two questions:
>
> - Do i need to change anything else in the source code to allow 
> the program to run with 500 loci?
> - Could I also increase this value further to allow analysis of 
> my full 602 loci dataset?
>
> Thank you!
>
> Samuel Wittwer


-- 
Bruce Rannala
Professor, Evolution & Ecology, UC Davis

**Comment by SamWittwer** [comment]
Hello Bruce

Thank you very much! Seems to work fine now, here's hoping I'm getting some meaningful results to discuss :-)

Can I suggest a slight change to the way the number seed is handled? If I am reading the manual correctly, the seed defaults to 10 unless otherwise specified. In my opinion it would make sense to maybe use system time or something similar as a default seed so distinct runs can be started without having to worry about forgetting to set the seed.

Beautiful program, easy to compile on stock ubuntu and very easy to work with. Thank you for your work!

Best wishes

Sam
